swagger: '2.0'
info:
  title: Peale Foundation API
  description: Peale Foundation APIs descriptions
  version: "1.0.0"
host: localhost:1337
schemes:
  - http
basePath: /v1
produces:
  - application/json
securityDefinitions:
  accessToken:
    type: "apiKey"
    name: "authorization"
    in: "header"
  accessAdminToken:
    type: "apiKey"
    name: "authorization"
    in: "header"
paths:
  /signin:
    put:
      summary: User signin.
      description: Sign in using the provided email and password combination.
      parameters:
      - name: UserCredentials
        in: body
        description: Username or Email account and credentials.
        required: true
        schema:
          $ref: '#/definitions/UserCredentials'
      tags:
      - Session
      responses:
        201:
          description: Session created
          schema:
            $ref: '#/definitions/SessionNew'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /signup:
    post:
      summary: User signup.
      description: Sign up using the provided username/email, password and password confirm.
      parameters:
      - name: UserCredentialsSignUp
        in: body
        description: Username or Email account, Password and Password Confirm.
        required: true
        schema:
          $ref: '#/definitions/UserCredentialsSignUp'
      tags:
      - Session
      responses:
        201:
          description: Account created succesfully.
          schema:
            $ref: '#/definitions/SessionNew'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /forgot-password:
    post:
      summary: Forgot password
      description: This action attempts to recovery password for one user account with the email/username provided.
      parameters:
      - name: UsernameForgotPassword
        in: body
        description: Username/Email for forgot password recovery.
        required: true
        schema:
          $ref: '#/definitions/UsernameForgotPassword'
      tags:
      - Session
      responses:
        201:
          description: An email has been sent, please check your inbox to reset you password.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sermons:
    get:
      summary: List of all sermons.
      description: Retrieve all sermons data.
      responses:
        200:
          description: Succesfully retrieved all sermons.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sermons/{id}:
    get:
      summary: Show one sermon.
      description: Retrieve one sermon data.
      parameters:
        - in: path
          name: id
          description: The sermon id.
          type: string
          required: true
      responses:
        200:
          description: Succesfully retrieved sermon.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sermons-me:
    get:
      summary: List of all sermons with personalized data User.
      description: Retrieve all sermons data.
      parameters:
        - in: header
          name: token
          description: Authorization token.
          type: string
          required: true
      tags:
      - Session
      responses:
        200:
          description: Succesfully retrieved all sermons.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sermons-me/{id}:
    get:
      summary: Show one sermon with personalized data User.
      description: Retrieve one sermon data.
      parameters:
        - in: header
          name: token
          description: Authorization token.
          type: string
          required: true
        - in: path
          name: id
          description: The sermon id.
          type: string
          required: true
      tags:
      - Session
      responses:
        200:
          description: Succesfully retrieved sermon.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'




definitions:
  UserCredentials:
    type: object
    properties:
      username:
        type: string
        description: User's username
      password:
        type: string
        description: User's password
  
  UserCredentialsSignUp:
    type: object
    properties:
      username:
        type: string
        description: User's username
      password:
        type: string
        description: User's password
      confirmPassword:
        type: string
        description: User's password confirm
  
  UsernameForgotPassword:
    type: object
    properties:
      username:
        type: string
        description: User's username

  SessionNew:
    type: object
    properties:
      accessToken:
        type: string
        description: User's session token
        format: jwt

  Error:
    type: object
    properties:
      statusCode:
        type: integer
        format: int32
      message:
        type: string
      error:
        type: string